eureka:
  client:
    service-url: 
      defaultZone: http://localhost:8000/eureka

server:
  port: 8001

spring:
  application:
    name: cloud-config-server
  cloud:
    config:
      server:
        git:
          uri: C:\Users\sgoyal1\Desktop\spring-boot\config
          search-paths:
          - /{application}/
          - /
